[environment]

# base URL of the application under test
base_url = https://www.saucedemo.com/

# browser type to be used for automation
browser = chrome

# default wait time in seconds
timeout = 10


[credentials]

# default username for login
username = standard_user

# default password for login
password = secret_sauce